### ISSUE TITLE
1.0.0 release breaks everything because index.js is an empty file

### ISSUE THREAD

**Issue by chrismbarr** [razvanz/jasmine2-reporter#22]
I updated form 0.3.1 to 1.0.0 and now nothing works. The [package file says `main: 'index.js'`](https://github.com/razvanz/jasmine2-reporter/blob/master/package.json#L5) but [that file is completely blank](https://github.com/razvanz/jasmine2-reporter/blob/master/index.js), thus nothing works.

```js
var reporter = require('jasmine2-reporter');
console.log(reporter);  //logs `{}` or `undefined`
```

**Comment by corvinrok** [comment]
I am getting a different error emanating from the same root cause-- the index is completely empty leaving any `new` based on its export/function/method definitions as `undefined`.  For example, trying to import and use the package inside of protractor in this kind of fashion:
```
let Jasmine2TestReporter = require('jasmine2-reporter').Jasmine2Reporter;
jasmine.getEnv().addReporter(new Jasmine2TestReporter({}));
```

leaves the following results:
```
E/launcher - Error: TypeError: Jasmine2TestReporter is not a constructor
    at onPrepare (C:\git\test-application\protractor.conf.js:56:38)
```

Obviously no one can use 1.0.0 as it is. Is anyone still maintaining this package?

**Comment by corvinrok** [comment]
@chrismbarr With the release 1.0.1, this issue is resolved.
